PROJECT = 'buck_converter'
DATA = '../data'
DEBUG_PEDAPP = True

ESR_FLAG = 'False'
ESR_Value = 0.01
ANALYSIS = 'TRANSIENT' # 1)OPERATING_POINT, 2)TRANSIENT, 3)AC_ANALYSIS, 4)DC_SWEEP
LIB_PATH = 'libraries'
DIODE_TYPE = '1N4148'
MOSFET_TYPE = 'irf150'
